### ISSUE TITLE
3.2.3 not supported. Please update to 3.3.0b1

### ISSUE THREAD

**Issue by maxsupermanhd** [snapcrafters/warzone2100#5]

**Comment by lucyllewy** [comment]
Could you be more specific on "not supported"? As far as I can tell, 3.2.3 is still the current stable release.

**Comment by popey** [comment]
Agreed. 3.2.3 is the latest stable release.

**Comment by past-due** [comment]
I believe this was opened because, at the moment, only 3.3.0_beta1 is supported for online multiplayer games.

(Despite being tagged as a "beta", 3.3.0_beta1 is substantially more stable than 3.2.3. This is a bit of a transitionary period to what will hopefully be more stable and frequent releases.)
